"""
Opens a PR on any public GitHub repo using a fork-based approach:
1. Fork the target repo into the authenticated user's account
2. Create a branch on the fork
3. Commit the generated pipeline to that branch
4. Open a PR from fork → original repo
5. Post AI review as a comment on the PR
"""

import asyncio
import base64
from datetime import datetime, timezone

import httpx

GITHUB_API = "https://api.github.com"
WORKFLOW_PATH = ".github/workflows/ci-generated.yml"


async def open_pr(
    owner: str,
    repo: str,
    token: str,
    pipeline_yaml: str,
    ai_review: str,
) -> str:
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    async with httpx.AsyncClient(headers=headers, timeout=30) as client:
        # Get authenticated user's login
        user_resp = await client.get(f"{GITHUB_API}/user")
        user_resp.raise_for_status()
        fork_owner = user_resp.json()["login"]

        # Get target repo's default branch
        repo_resp = await client.get(f"{GITHUB_API}/repos/{owner}/{repo}")
        repo_resp.raise_for_status()
        default_branch = repo_resp.json()["default_branch"]

        # Fork the repo (no-op if fork already exists)
        fork_resp = await client.post(f"{GITHUB_API}/repos/{owner}/{repo}/forks")
        if fork_resp.status_code not in (200, 202):
            raise RuntimeError(f"Failed to fork repo: {fork_resp.status_code} — {fork_resp.text}")

        # Wait for fork to be ready (GitHub forks are async)
        fork_ready = False
        for _ in range(10):
            await asyncio.sleep(3)
            check = await client.get(f"{GITHUB_API}/repos/{fork_owner}/{repo}")
            if check.status_code == 200:
                fork_ready = True
                break
        if not fork_ready:
            raise RuntimeError("Fork did not become ready in time. Please try again.")

        # Get default branch SHA from the fork
        ref_resp = await client.get(
            f"{GITHUB_API}/repos/{fork_owner}/{repo}/git/ref/heads/{default_branch}"
        )
        ref_resp.raise_for_status()
        base_sha = ref_resp.json()["object"]["sha"]

        # Create new branch on the fork
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
        branch_name = f"ai-pipeline-{timestamp}"

        branch_resp = await client.post(
            f"{GITHUB_API}/repos/{fork_owner}/{repo}/git/refs",
            json={"ref": f"refs/heads/{branch_name}", "sha": base_sha},
        )
        branch_resp.raise_for_status()

        # Commit the pipeline file to the branch on the fork
        commit_resp = await client.put(
            f"{GITHUB_API}/repos/{fork_owner}/{repo}/contents/{WORKFLOW_PATH}",
            json={
                "message": "feat: add AI-generated CI/CD pipeline",
                "content": base64.b64encode(pipeline_yaml.encode()).decode(),
                "branch": branch_name,
            },
        )
        if commit_resp.status_code not in (200, 201):
            raise RuntimeError(
                f"Failed to commit pipeline file: {commit_resp.status_code} — {commit_resp.text}"
            )

        # Open PR from fork branch → original repo default branch
        pr_resp = await client.post(
            f"{GITHUB_API}/repos/{owner}/{repo}/pulls",
            json={
                "title": "feat: Add AI-generated CI/CD pipeline",
                "body": (
                    "## AI-Generated CI/CD Pipeline\n\n"
                    "This PR was automatically generated by "
                    "[ai-pipeline-generator](https://github.com/soumeet96/ai-pipeline-generator) "
                    "based on your repository's detected tech stack.\n\n"
                    "The pipeline was reviewed by an AI before this PR was opened.\n\n"
                    "Please review and merge when ready."
                ),
                "head": f"{fork_owner}:{branch_name}",
                "base": default_branch,
            },
        )
        pr_resp.raise_for_status()
        pr_data = pr_resp.json()
        pr_number = pr_data["number"]
        pr_url = pr_data["html_url"]

        # Post AI review as a comment on the PR
        review_body = (
            "## 🤖 AI Pipeline Review (powered by Groq + Llama 3.3)\n\n"
            + ai_review
            + "\n\n---\n*Generated by [ai-pipeline-generator](https://github.com/soumeet96/ai-pipeline-generator)*"
        )
        await client.post(
            f"{GITHUB_API}/repos/{owner}/{repo}/issues/{pr_number}/comments",
            json={"body": review_body},
        )

        return pr_url
