"""
Opens a PR on the target GitHub repo with the generated pipeline.
Then posts an AI review comment on that PR.
"""

import base64
from datetime import datetime, timezone

import httpx

GITHUB_API = "https://api.github.com"
WORKFLOW_PATH = ".github/workflows/ci-generated.yml"


async def open_pr(
    owner: str,
    repo: str,
    token: str,
    pipeline_yaml: str,
    ai_review: str,
) -> str:
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    async with httpx.AsyncClient(headers=headers, timeout=20) as client:
        # Get default branch and its SHA
        repo_resp = await client.get(f"{GITHUB_API}/repos/{owner}/{repo}")
        repo_resp.raise_for_status()
        default_branch = repo_resp.json()["default_branch"]

        ref_resp = await client.get(
            f"{GITHUB_API}/repos/{owner}/{repo}/git/ref/heads/{default_branch}"
        )
        ref_resp.raise_for_status()
        base_sha = ref_resp.json()["object"]["sha"]

        # Create new branch
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
        branch_name = f"ai-pipeline-{timestamp}"

        await client.post(
            f"{GITHUB_API}/repos/{owner}/{repo}/git/refs",
            json={"ref": f"refs/heads/{branch_name}", "sha": base_sha},
        )

        # Commit the pipeline file to the new branch
        content_b64 = base64.b64encode(pipeline_yaml.encode()).decode()
        await client.put(
            f"{GITHUB_API}/repos/{owner}/{repo}/contents/{WORKFLOW_PATH}",
            json={
                "message": "feat: add AI-generated CI/CD pipeline",
                "content": content_b64,
                "branch": branch_name,
            },
        )

        # Open the PR
        pr_resp = await client.post(
            f"{GITHUB_API}/repos/{owner}/{repo}/pulls",
            json={
                "title": "feat: Add AI-generated CI/CD pipeline",
                "body": (
                    "## AI-Generated CI/CD Pipeline\n\n"
                    "This PR was automatically generated by "
                    "[ai-pipeline-generator](https://github.com/soumeet96/ai-pipeline-generator) "
                    "based on your repository's tech stack.\n\n"
                    "Please review the pipeline and merge when ready."
                ),
                "head": branch_name,
                "base": default_branch,
            },
        )
        pr_resp.raise_for_status()
        pr_data = pr_resp.json()
        pr_number = pr_data["number"]
        pr_url = pr_data["html_url"]

        # Post AI review as a comment on the PR
        review_body = (
            "## 🤖 AI Pipeline Review (powered by Groq + Llama 3.3)\n\n"
            + ai_review
            + "\n\n---\n*Generated by [ai-pipeline-generator](https://github.com/soumeet96/ai-pipeline-generator)*"
        )
        await client.post(
            f"{GITHUB_API}/repos/{owner}/{repo}/issues/{pr_number}/comments",
            json={"body": review_body},
        )

        return pr_url
